services:
  aggregator:
    build: ./aggregator
    environment:
      DATABASE_URL: postgresql://user:pass@storage:5432/db
      REDIS_URL: redis://broker:6379/0
      WORKERS: "4"
      QUEUE_NAME: "logq"
    ports:
      - "8080:8080"
    depends_on:
      - storage
      - broker

  publisher:
    build: ./publisher
    environment:
      TARGET_URL: http://aggregator:8080/publish
      TOTAL: "20000"
      DUP_RATE: "0.3"
      TOPICS: "app.auth,app.pay,app.order"
    depends_on:
      - aggregator

  broker:
    image: redis:7-alpine
    ports: []            # internal only
    volumes:
      - broker_data:/data

  storage:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports: []            # internal only
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  broker_data:
